[build]
    functions = "functions"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[dev]
    functionsPort = 8888
    targetPort = 8080
    staticServerPort = 8080
    port = 8000